### ISSUE TITLE
Require only SDL2.0.2, not 2.0.3

### ISSUE THREAD

**Issue by svenpanne** [haskell-game/sdl2#102]
Neither Ubuntu nor Debian have packages for 2.0.3 in their latest releases (so Mint probably doesn't have it, either), and according to https://hg.libsdl.org/SDL/file/e12c38730512/WhatsNew.txt#l96 there is no need for them to upgrade, because 2.0.2 => 2.0.3 fixed only a Mac OS X issue. To make things much, much easier for users of the top 3 used Linux distros, it would be good to lower `pkgconfig-depends:` from `sdl2 >= 2.0.3` to `sdl2 >= 2.0.2`.

(Yes, I know how to install newer SDL2 versions by hand, but that't not the point here. :wink: )

**Comment by polarina** [comment]
Thanks! I've reduced the lower bound with ccf61b7033ffde01111c4246c9d52004b3650a4a. Can you test and see if it works for you?

**Comment by ocharles** [comment]
But 2.0.4 is out now - do we want that?

**Comment by polarina** [comment]
@ocharles Yes, once we have bindings to the new functionality in SDL2 2.0.4.

**Comment by svenpanne** [comment]
Yes, the patch works, thanks. Regarding 2.0.4: It would be great if the `sdl2` package will still support older versions, otherwise you'll probably lose tons of users who probably aren't even interested in the brand-new stuff. (Yes, installing SDL2 from source is not that hard, but nevertheless, every additional step will scare away a significant fraction of potential users.) I can see basically 2 options:

* Introduce a cabal flag with `manual: False` (the default) for the new stuff, and this flags guards the `pkgconfig-depends:` version. If I see this correctly, cabal should first try to build with one version, then the other.
* Switch to dynamic binding of the API entries, just like `OpenGLRaw` or `gl`. This is the most flexible approach and makes it e.g. even possible to build the full package on machines with older libraries and avoids the need for a flag.

**Comment by ocharles** [comment]
Is it possible to just statically compile sdl2 into this library?

**Comment by svenpanne** [comment]
Static linking on Linux/Mac OS X should be possible (don't know about Windows), but I wouldn't really recommend it. You get all the common problems, like not being able to update the linked-in library alone, perhaps needing some patches from distros to make them work there, getting lots of failed builds because the native library won't compile or doesn't work correctly, license problems, etc. etc.  Basically you suddenly maintain/package *two* projects instead of one. IMHO all that work is better spent into e.g. making the SDL binding more dynamic by using `dlopen` and friends to access whatever is usable on the given platform. Just my 2c... :wink:

**Comment by svenpanne** [comment]
Fixed by ccf61b7033ffde01111c4246c9d52004b3650a4a
