### ISSUE TITLE
Unable to switch to windowed from fullscreen

### ISSUE THREAD

**Issue by Th30n** [haskell-game/sdl2#103]
When a window's mode is Fullscreen, it is not possible to switch to windowed by calling
`setWindowMode window Windowed`.

As far as I can tell, the reason is that `setWindowMode` calls `Raw.restoreWindow` which does nothing on fullscreen windows.

Some possible solutions:
- Call `Raw.setWindowFullscreen w 0` and then `Raw.restoreWindow w`.
- Add another WindowMode, e.g. Restore (but that kinda defeats the reuse for WindowConfig)
- Simply add a non raw call to `restoreWindow` and `setWindowMode` only uses `setWindowFullscreen`

**Comment by polarina** [comment]
This should be resolved with 789383f447ec80995a5a3c6c8d3be77590cdcc83. Thanks!
