### ISSUE TITLE
Please consider exposing `SDL.Exception`

### ISSUE THREAD

**Issue by cies** [haskell-game/sdl2#105]
Since I'm updating the [hssdl2-gfx](https://github.com/keera-studios/hssdl2-gfx) (doing it [over here](https://github.com/cies/sdl2-gfx), not much to see yet) library to be in line with `sdl2`, I'd like to reuse as much as possible. Currently I cannot re-use your clever exception techniques, which is a pity.

Possibly first put it under an `Internal` submodule.

Thanks for considering.

**Comment by cies** [comment]
This is not needed for _me_ anymore; I've decided to go with `sld2-cairo` instead of `SDL2_gfx`.

It might be helpful for someone else in the future though.

Feel free to close.

**Comment by sbidin** [comment]
I'd love `SDL.Exception` to be exposed as well.

Since it's been hidden, I've resorted to duplicating your code in all of my wrappers, [like here for sdl2-image](https://github.com/sbidin/sdl2-image/blob/master/src/SDL/ExceptionHelper.hs).

**Comment by polarina** [comment]
Should be addressed with 134edef3088f9ea87b7025317b0c0f20fb8fe629. Let us know if there's anything else needed.
