### ISSUE TITLE
audioExample doesn't work

### ISSUE THREAD

**Issue by vanzef** [haskell-game/sdl2#110]
I've built latest (from git) audioExample with GHC 7.10.3 and sdl2 2.1.1 version (from NixOS repos).

When I run it in ghci (`cabal repl`) it works almost well, but there is some glitches with sound. But when I try to run compiled version (`cabal run`), there are 3 different ways it fails:

> It plays a sound for a second or shorter and freezes, so I can only kill it

Second way is this one:
> audioExample: internal error: audioExample: internal error: scavenge: unimplemented/strange closure type 41049 @ 0x7f30e29f1fa8
>    (GHC version 7.10.3 for x86_64_unknown_linux)
>    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
>scavenge: unimplemented/strange closure type 41049 @ 0x7f30e29f1fa8
>    (GHC version 7.10.3 for x86_64_unknown_linux)
>    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
> zsh: abort      cabal run`

And the last one -- just segfault.

What should I do? Check my sdl2 lib, GHC or something else?

**Comment by Rydgel** [comment]
Do you compile the example with the `-threaded` option?

**Comment by vanzef** [comment]
No, I don't. Should I?

**Comment by AndrewRademacher** [comment]
Adding -threaded fixed all of my stability issues, things like the error described above and the occasional, set fault.

**Comment by vanzef** [comment]
It seems to solve my problem. Thanks!
