### ISSUE TITLE
Unable to cabal install w/ vanilla GHC 8.0.1 + cabal-install 1.24.0.0 (OR: karma backlash for depending on linear)

### ISSUE THREAD

**Issue by mgmeier** [haskell-game/sdl2#114]
Can anyone confirm? cabal-install produces the following error:
```
$ cabal install sdl2-2.1.1 --dry-run
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: sdl2-2.1.1 (user goal)
trying: vector-0.11.0.0/installed-6uB... (dependency of sdl2-2.1.1)
next goal: primitive (dependency of vector-0.11.0.0/installed-6uB...)
rejecting: primitive-0.6.1.0/installed-Ip4... (conflict: primitive =>
transformers==0.5.2.0/installed-0.5..., sdl2 => transformers>=0.2 && <0.5)
rejecting: primitive-0.6.1.0, primitive-0.5.4.0, primitive-0.5.3.0,
primitive-0.5.2.1, primitive-0.5.1.0, primitive-0.5.0.1, primitive-0.5,
primitive-0.4.1, primitive-0.4.0.1, primitive-0.4, primitive-0.3.1,
primitive-0.3, primitive-0.2.1, primitive-0.2, primitive-0.1, primitive-0.6
(conflict: vector => primitive==0.6.1.0/installed-Ip4...)
Dependency tree exhaustively searched.
```

This rejection of primitive >= 0.6 seems to have its origin in the linear package.

Please, dear sdl2 author(s): whilst I see the theoretical beauty of using an external data type for point and color vectors (e.g. V2 or V4 of linear): the linear package is absolute bloatware defining myriads of instances completely unnecessary to your use case. Furthermore it depends on lens for no good reason except to save a little bit of boilerplate in its source text, without improving its (human-)readability at all in any way. 

This is the already the second time, this combo of linear + sdl2 blows up in my face during the last 3 months. The last time I wrote a castrated (i.e., removing offending/unsatisfiable dependencies) drop-in fork (see my account on github) of linear, removing a lot of code in the process, showing that it's an absolute overkill to use in this case (I'm using sdl2 in production).

I urge you, I beg you, dear authors: get rid of that package. For sdl2's use case, it's overkill. Anyone using some engine on top of SDL2 rendering, will have their own data types + instances + algorithms anyway (or indeed be using linear), to do the math, and then convert to sdl2's types.

Please please please please please please please please get rid of it. It doesn't add value, it just adds pain.

**Comment by mgmeier** [comment]
Addendum: I gather this would be a deeper conceptual change in the bindings. Iif you want to open a discussion with users of the sdl2 package about that on IRC / wiki / ... please let me know so I can make my point.

**Comment by nxths** [comment]
linear 1.20.5 fixed this (uploaded 5/29), but you'll need to also need to edit the transformer upper bounds in the meantime
https://www.reddit.com/r/haskellgamedev/comments/4jpthu/windows_sdl2_is_now_almost_painless_via_stack/d3rgk74

**Comment by mgmeier** [comment]
Thx for the heads-up. As I said before, I'm using my fork of linear, with overeager upper bounds and gazillions of unnecessary instances and package dependencies removed. That works just fine.

I wanted to know if sdl2 maintainers would give any thought on removing dependencies on half of hackage and avoiding considerable code bloat and frequent inability to consistently build, just to use a rather flat and dumb data type. Any opinions in that regard (I'm aware my question was highly suggestive :p)?

**Comment by tejon** [comment]
Half-of-hackage dependency can now be removed with the `no-linear` flag. And transformers bounds are good, too. :)
