### ISSUE TITLE
transformers upper bound are too restrictive

### ISSUE THREAD

**Issue by ghorn** [haskell-game/sdl2#115]

**Comment by nitrix** [comment]
Using stackage resolver nightly-2016-06-21, seeing the same issue.

This is preventing me to migrate my project to GHC 8.0.1 (which would take care of #41)

Relevant errors:

--  Failure when adding dependencies:    
      transformers: needed (>=0.2 && <0.5), 0.5.2.0 found (latest applicable is 0.4.3.0)
    needed for package sdl2-2.1.0

**Comment by ocharles** [comment]
I believe this is fixed now, right @tejon ?

**Comment by tejon** [comment]
Yes, sorry... didn't think to go back through issues when I was merging PRs!
