### ISSUE TITLE
Audio example has a sound skipping bug

### ISSUE THREAD

**Issue by Lokathor** [haskell-game/sdl2#133]
In the audio example, the `sinSamples` list is Int16, which is correct, but the sample *index* (the `n` value input) is also Int16, which is incorrect. The input type to the map needs to be changed to Int32 or there will be a skipping sound during playback when the index wraps. Probably Int32 will still have a skip during a wrapping point, but just far far less frequently.

https://github.com/haskell-game/sdl2/blob/master/examples/AudioExample.hs#L18

**Comment by ocharles** [comment]
This is true, but I won't have time to fix it. If anyone wants to submit a PR, by all means go ahead.
