### ISSUE TITLE
Add new SDL 2.0.4 functions

### ISSUE THREAD

**Issue by polarina** [haskell-game/sdl2#136]
I would like to add exports for new functions found in the SDL 2.0.4 release. The runtime does not like foreign imports of symbols that are not present in the linked C library, thus would make SDL 2.0.4 the minimum required version.

Are there any reasons we would like to wait with exposing the new functions at this point in time?

**Comment by tejon** [comment]
Nothing wrong with it IMO. Anyone for some reason stuck on 2.0.2/2.0.3 can specify package versions; or if they're using Stackage, a whole snapshot (no chasing transient dependency bounds).

If there are any other short-term improvements that can be done without that bump, maybe do them first (or bump a large enough version number that you can backport them, though that doesn't play as well with Stackage).

Also, I'd wait until just after a Stackage LTS release.

**Comment by ocharles** [comment]
I think this might be OK. Ubuntu 16.04 LTS contains SDL 2.0.4, so this doesn't put to close to the bleeding edge.

**Comment by polarina** [comment]
Implemented with 41bbd81495872259a405a61f662cef0871dc96a2.
