### ISSUE TITLE
sdl2.cabal on hackge differs from version on github

### ISSUE THREAD

**Issue by nek0** [haskell-game/sdl2#137]
can you please put the github version ov sdl2.cabal on hackage? I depend on SDL.Internal.NUmbered and would like to use standard cabal install.

Thanks.

**Comment by polarina** [comment]
I have a few changes I'd ideally like to get done before a release. Either way, I'll make you a new release on Sunday the latest, unless someone else decides to do one earlier.

**Comment by polarina** [comment]
sdl2-2.2.0 has been released on Hackage. Enjoy!
