### ISSUE TITLE
Bugs in createCursor and createSystemCursor

### ISSUE THREAD

**Issue by KolodeznyDiver** [haskell-game/sdl2#138]
In SDL.Input.Mouse: `createCursor :: MonadIO m => V.Vector Bool -> V.Vector Bool  -> .....`
Must be: `V.Vector Word8 ->V.Vector Word8 ` .

createSystemCursor absent in SDL.Input.Mouse, although there is in SDL.Raw.Event

**Comment by dpwiz** [comment]
in favor of #232
