### ISSUE TITLE
Failed to load interface for ‘Paths_sdl2’ in lazyfoo examples

### ISSUE THREAD

**Issue by madjestic** [haskell-game/sdl2#141]
[as seen in here and probably others:](https://github.com/haskell-game/sdl2/tree/master/examples/lazyfoo)
```
Lesson02.hs:9:1: error:
    Failed to load interface for ‘Paths_sdl2’	
    Perhaps you meant Paths_fgl
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
```

**Comment by ocharles** [comment]
Could you explain how to reproduce this? It sounds like you aren't compiling the examples using Cabal.

**Comment by madjestic** [comment]
I think the lazyfoo [examples supplied with the sdl2](https://github.com/haskell-game/sdl2/tree/master/examples/lazyfoo) need to be updated, according to the latest:
[https://github.com/palf/haskell-sdl2-examples](https://github.com/palf/haskell-sdl2-examples)

**Comment by madjestic** [comment]
I am sorry, it looks like it's my fault, as I was not looking at the latest version...
