### ISSUE TITLE
High-level bindings should distinguish between finger down / motion / up

### ISSUE THREAD

**Issue by nickkuk** [haskell-game/sdl2#156]
At now raw events SDL_FINGERDOWN, SDL_FINGERMOTION, SDL_FINGERUP [maps](
https://github.com/haskell-game/sdl2/blob/f97390350bd43e052a558462c4a2aba9243b81de/src/SDL/Raw/Types.hsc#L548) to the same Raw.TouchFingerEvent - it saves typ,- then it [maps](https://github.com/haskell-game/sdl2/blob/master/src/SDL/Event.hs#L674) to TouchFingerEventData discarding typ, so we can't distinguish between these events.
TouchFingerEventData hasn't [InputMotion](https://github.com/haskell-game/sdl2/blob/master/src/SDL/Event.hs#L504) like keyboard and mouse.

I can add PR with
- TouchFingerEventData with added InputMotion - for SDL_FINGERDOWN and SDL_FINGERUP;
- new TouchFingerMotionEventData (= previous TouchFingerEventData) - for SDL_FINGERMOTION,

but it will be breaking change.
Can you suggest better approach / names?

**Comment by polarina** [comment]
Your suggested approach sounds good. It's consistent with how mouse events are currently represented.
