### ISSUE TITLE
Missing (or bad) header file: SDL.h (Windows 10)

### ISSUE THREAD

**Issue by VitorCBSB** [haskell-game/sdl2#161]
Following the instructions in this link: [Windows SDL2 is now almost painless via stack: haskellgamedev](https://www.reddit.com/r/haskellgamedev/comments/4jpthu/windows_sdl2_is_now_almost_painless_via_stack/)

I'm unable to get past the `stack build` part, getting this error message:

```
C:\Users\Vitor Coimbra\sdl2>stack build
sdl2-2.2.0: configure (lib)
Configuring sdl2-2.2.0...
Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe: Missing dependencies on foreign
libraries:
* Missing (or bad) header file: SDL.h
* Missing C libraries: SDL2, mingw32, SDL2main, SDL2
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

--  While building package sdl2-2.2.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.stack-work\dist\ca59d0ab configure "--with-ghc=C:\\Users\\Vitor Coimbra\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2\\bin\\ghc.EXE" "--with-ghc-pkg=C:\\Users\\Vitor Coimbra\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2\\bin\\ghc-pkg.EXE" --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\62cfb14b\pkgdb "--package-db=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\pkgdb" "--libdir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\lib" "--bindir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\bin" "--datadir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\share" "--libexecdir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\libexec" "--sysconfdir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\etc" "--docdir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\doc\\sdl2-2.2.0" "--htmldir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\doc\\sdl2-2.2.0" "--haddockdir=C:\\Users\\Vitor Coimbra\\sdl2\\.stack-work\\install\\6c953ab2\\doc\\sdl2-2.2.0" --dependency=StateVar=StateVar-1.1.0.4-5dJbnTVECtEAhfJXPZKdbO --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=exceptions=exceptions-0.8.3-ADEDRATtUrMK1JW4zMQ9U --dependency=linear=linear-1.20.6-FPSIwgzNt9R7bsq2wXRklJ --dependency=text=text-1.2.2.2-9UQZjEJZQFSGMffj1Z5g00 --dependency=transformers=transformers-0.5.2.0 --dependency=vector=vector-0.12.0.1-692PQMDMB6pIQ1uGwefDcQ "--extra-include-dirs=C:\\Users\\Vitor Coimbra\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\mingw64\\include" "--extra-lib-dirs=C:\\Users\\Vitor Coimbra\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\mingw64\\lib" --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
```

I have no idea what could be causing this, but one thing that has caused issues in unrelated projects is the fact that one of my directories has a space character in it (if this turns out to be the issue, this will make it project number 4 that I've personally had this break).

Someone else in the comments (EDIT: [comment here](https://www.reddit.com/r/haskellgamedev/comments/4jpthu/windows_sdl2_is_now_almost_painless_via_stack/d3kbp1g)) also has this very same problem, but with no resolution to it. I was hoping somebody could take a closer look at it.

Thanks in advance.

**Comment by Mikolaj** [comment]
Does it work if you remove the space?

**Comment by VitorCBSB** [comment]
It's not very simple for me to remove the space in my path as it's my Windows username and changing it breaks a ton of other things (PATH entries, for instance).

**Comment by Mikolaj** [comment]
OK. I have no clue about Windows. I naively thought you can just create a directory, like `C:\tmp\foo\sdl2`, give it proper permissions and repeat the process there.

**Comment by VitorCBSB** [comment]
The thing is that it seems to install SDL2 correctly, but for some reason can't find it in MSYS's directories (which reside inside my user directory):

```
C:\\Users\\Vitor Coimbra\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\mingw64\\lib
C:\\Users\\Vitor Coimbra\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\mingw64\\include
```

Oddly, two days ago I installed [TagLib](http://taglib.org/) this very same way (pacman) and was able to use [htaglib](https://hackage.haskell.org/package/htaglib), which has it as a foreign dependency, with no issues. I don't know how dependencies are being searched and why it works for one case but not the other.

My space character suspicion came mostly because of my previous experiences and because the other person that reported it (in the reddit link) also has them in his / her path.

**Comment by Mikolaj** [comment]
I'm wondering, perhaps the stack community would have some advice or perhaps there is a stack (or cabal?) issue, open or closed, about that?

I don't have Windows, so I couldn't possibly help you. My only experience with that is via AppVeyor, where I'm able to install sdl2 correctly from source and use it in another program: https://github.com/LambdaHack/LambdaHack/blob/038ae12ce6358ca383c692379115f3211c7aae2a/appveyor.yml

**Comment by Crysikrend** [comment]
I'm sorry that this issue has been open for so long with no answers, but I'll post a reply just in case people look at this issue later down the line, it may or may not help people.

So I'm struggling with this too, but I just need to double check that you have run the command 

```stack exec -- pacman -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2```

Which should install SDL's stuff via pacman. I don't know if there are any other ways of installing SDL2, but my header file can be found at least. Also, ensure everything is on your path via environment variables. Not very clued up on whether it should or shouldn't be found by default, but I know that I have SDL located at C:/SDL2-2.0.8 etc, and I've added that to my path for when I work with C++ etc.

Sorry I can't be much more help, I'm not good at this either and I'm struggling with actually compiling SDL so..

**Comment by VitorCBSB** [comment]
Quick update on this, I think we managed to track down the cause of this issue [(relevant issue)](https://github.com/haskell/cabal/issues/5519), so since this isn't actually an SDL2-specific problem, I'll be closing this.
