### ISSUE TITLE
No docs on hackage

### ISSUE THREAD

**Issue by Mikolaj** [haskell-game/sdl2#164]
I've finally managed to install new libsdl2-dev and libsd2-ttf-dev on the hackage docs building server. Could you restart doc building so that we can see if it works? Thanks!

**Comment by Mikolaj** [comment]
OK, never mind, the sdl2 packages I installed are too old, because the Ubuntu installation is too old. Too bad. Closing. :(

**Comment by ocharles** [comment]
Well, it's still a valid issue because we have no docs. But that is fixed now, too - I uploaded some manual docs.

Does the doc building fail with the `libsdl2-dev` used?

**Comment by Mikolaj** [comment]
Thank you for the manual docs. And to answer your question:

https://github.com/haskell/hackage-server/issues/608
https://github.com/haskell/hackage-server/issues/595
