### ISSUE TITLE
getRelativeMouseLocation should not return Point

### ISSUE THREAD

**Issue by andersk** [haskell-game/sdl2#169]
The whole point of the `Point` wrapper is to distinguish an absolute location from a relative offset, so `getRelativeMouseLocation` should not use it; it should return `V2 CInt`.

Probably `getModalMouseLocation` shouldn’t unconditionally return `Point` either, since they may be absolute or relative. (Perhaps something like `data Location = Absolute (Point V2 CInt) | Relative (V2 CInt)` would be a better result type, but `V2 CInt` seems reasonable enough.)

**Comment by ocharles** [comment]
Agreed, will happily take a PR.
