### ISSUE TITLE
Cairo on Retina screen

### ISSUE THREAD

**Issue by chrisdone** [haskell-game/sdl2#172]
Pinging @apirogov because this is about sdl2-cairo and sdl. I'm not sure which is the problem.

On my trivial Haskell web browser https://github.com/chrisdone/wish You can see that the rendering of the text is slightly blurry where it's been scaled to 2-ish the size it should be. I believe that the canvas created by Cairo and the drawing canvas for SDL are not in sync. 

I'm not sure whether this out of syncness comes from SDL or Cairo. See e.g. Chrome vs Wish (click the picture to see it at full scale or you won't see the pixelation):

<img width="851" alt="screenshot 2017-10-19 11 49 36" src="https://user-images.githubusercontent.com/11019/31767623-b0e95e64-b4c3-11e7-8786-93a16851c7a4.png">

Here is some repro code:

``` haskell
{-# LANGUAGE OverloadedStrings #-}

import qualified Data.Text as T
import           Linear.V2 (V2(..))
import qualified SDL as SDL
import qualified SDL.Cairo as Cairo
import qualified SDL.Cairo.Canvas as Canvas
import           SDL.Event as SDL
import           SDL.Vect

main :: IO ()
main = do
  SDL.initializeAll
  version <- SDL.version
  putStrLn $ "SDL Version: " ++ show version
  let windowConfig =
        SDL.WindowConfig
        { SDL.windowBorder = True
        , SDL.windowHighDPI = True
        , SDL.windowInputGrabbed = False
        , SDL.windowMode = SDL.Windowed -- SDL.FullscreenDesktop
        , SDL.windowOpenGL = Nothing
        , SDL.windowPosition = SDL.Absolute (P $ V2 10 10)
        , SDL.windowResizable = True
        , SDL.windowInitialSize = V2 150 150
        }
  window <- SDL.createWindow (T.pack "MyApp") windowConfig
  config <- SDL.getWindowConfig window
  putStrLn $ "Flags: " ++ show config
  renderer <-
    SDL.createRenderer
      window
      (-1)
      SDL.defaultRenderer {SDL.rendererType = SDL.SoftwareRenderer}
  texture0 <- Cairo.createCairoTexture renderer (V2 150 150)
  Canvas.withCanvas
    texture0
    (do Canvas.background $ Canvas.rgb 255 255 255
        Canvas.textFont (Canvas.Font "Arial" 14 False False)
        Canvas.text "Hello, World!" (V2 50 50))
  SDL.copy renderer texture0 Nothing Nothing
  SDL.present renderer
  let loop = do
        event <- waitEvent
        case eventPayload event of
          QuitEvent -> return ()
          _ -> loop
  loop
```

The output looks like this:

<img width="167" alt="screenshot 2017-10-19 12 07 01" src="https://user-images.githubusercontent.com/11019/31768212-43c72c0a-b4c6-11e7-9212-325dbd86658e.png">

Note the difference between the text in the window title and the cairo text.

Adjusting the dimensions to `createCairoTexture` doesn't help, the picture is either too pixelated or too large. And `SDL.windowHighDPI = True` doesn't make a difference to the rendering at all.

I basically just want to show a Cairo canvas on the screen unmodified without any artificial scaling. I'd love to make some more apps with SDL, but if I'm going to be serious about it then I really need text that actually looks good. I'm not sure the solution is entirely straight-forward, but opening this issue so at least it's tracked.

**Comment by chrisdone** [comment]
Pinging @biglambda and @matthewleon, as you are both on Retina and I took the repro code from your example to make mine. Any ideas?

**Comment by biglambda** [comment]
I think the solution to this is qtah instead of SDL but I haven't done it yet.

**Comment by chrisdone** [comment]
That'd be a pity as SDL works great other than this one detail.

**Comment by chrisdone** [comment]
**Success!** 🎉  👏 

Before and after:

<img width="167" alt="screenshot 2017-10-19 12 07 01" src="https://user-images.githubusercontent.com/11019/31822976-78ebe89e-b5a2-11e7-9859-d6c4d6681ec7.png">

<img width="178" alt="screenshot 2017-10-20 14 19 33" src="https://user-images.githubusercontent.com/11019/31822813-e3112802-b5a1-11e7-9415-f1a94d8ee0b5.png">

It was running in high DPI mode the whole time! The confusing part is that you create a window of 800x800 but this really makes a window of twice that size. You then have to query with `glGetDrawableSize` to see the real pixels, as these are at the scale you are working with when you do everything else afterwards. This also explains why my original screenshot's title bar is properly crisp; because it was in high DPI mode the whole time. **When you're not in high DPI mode, even the title bar is blurry.**

Crucially, you have to create the Cairo surface using this data,

``` haskell 
texture0 <- Cairo.createCairoTexture renderer drawingSize
```
You can also use the ratio of getDrawableSize and the size you specified for the window to aid in producing a reasonable font size.

I'm going to put the `glGetDrawableSize` in a wrapped high-level function in `SDL.Video` and put a recommendation in the docs.

``` haskell
{-# LANGUAGE OverloadedStrings #-}

import           Foreign
import           Linear.V2 (V2(..))
import qualified SDL as SDL
import qualified SDL.Cairo as Cairo
import qualified SDL.Cairo.Canvas as Canvas
import           SDL.Event as SDL
import           SDL.Internal.Types
import           SDL.Raw.Video

main :: IO ()
main = do
  SDL.initializeAll
  let windowConfig =
        SDL.WindowConfig
        { SDL.windowBorder = True
        , SDL.windowHighDPI = True
        , SDL.windowInputGrabbed = False
        , SDL.windowMode = SDL.Windowed
        , SDL.windowOpenGL = Nothing
        , SDL.windowPosition = SDL.Wherever
        , SDL.windowResizable = True
        , SDL.windowInitialSize = V2 150 150
        }
  window <- SDL.createWindow "MyApp" windowConfig
  wPtr <- malloc
  hPtr <- malloc
  glGetDrawableSize
    (let Window p = window
     in p)
    wPtr
    hPtr
  drawingSize <- V2 <$> peek wPtr <*> peek hPtr
  free wPtr
  free hPtr
  renderer <- SDL.createRenderer window (-1) SDL.defaultRenderer
  texture0 <- Cairo.createCairoTexture renderer drawingSize
  Canvas.withCanvas
    texture0
    (do Canvas.background $ Canvas.rgb 255 255 255
        Canvas.textFont (Canvas.Font "Arial" 30 False False)
        Canvas.text "Hello, World!" (V2 50 50))
  SDL.copy renderer texture0 Nothing Nothing
  SDL.present renderer
  let loop = do
        event <- waitEvent
        case eventPayload event of
          QuitEvent -> return ()
          _ -> loop
  loop
```

**Comment by chrisdone** [comment]
Scratch that, the following is enough:

``` haskell
Just (SDL.Rectangle _ viewport) <- SDL.get (SDL.rendererViewport renderer)
texture0 <- Cairo.createCairoTexture renderer viewport
```

**Comment by chrisdone** [comment]
**ALSO CRUCIAL**: Turn off software rendering!

``` haskell  
SDL.defaultRenderer {SDL.rendererType = SDL.SoftwareRenderer}
```

Don't use that renderType!

**Comment by ocharles** [comment]
It sounds like you have what you want - superb! Is there anything we need to change or documentation that we need to improve in `sdl2`?

**Comment by chrisdone** [comment]
I can add a "For high DPI displays (OS X, Windows) see "Retina" section." and make a little retina section with these tips. I discovered this through trial and error so it'll save other people pain.

**Comment by nickkuk** [comment]
At now there is only a line in ChangeLog.md
`Expose glGetDrawableSize (can differ from window size in some environments).`

I think we can add remark from [https://wiki.libsdl.org/SDL_GetWindowSize](https://wiki.libsdl.org/SDL_GetWindowSize) to [windowSize](https://github.com/haskell-game/sdl2/blob/9351d0a521a4c0b2b828291cdcbc9156a3dd486e/src/SDL/Video.hs#L295) and [windowInitialSize](https://github.com/haskell-game/sdl2/blob/9351d0a521a4c0b2b828291cdcbc9156a3dd486e/src/SDL/Video.hs#L187).

**Comment by nickkuk** [comment]
I've added some documentation. I didn't write about `SDL.get (SDL.rendererViewport renderer)`, because this variable changes over time. You can be sure that it will return what you need only in a moment after window creation.
