### ISSUE TITLE
Simple example application with Renderer fails with ExitFailure (-11)

### ISSUE THREAD

**Issue by turion** [haskell-game/sdl2#181]
Consider this example code:
```haskell
{-# LANGUAGE OverloadedStrings #-}
import SDL

main :: IO ()
main = do
  initializeAll
  window <- createWindow "My SDL Application" defaultWindow
  renderer <- createRenderer window (-1) defaultRenderer
  appLoop renderer

appLoop :: Renderer -> IO ()
appLoop renderer = do
  rendererDrawColor renderer $= V4 0 0 255 255
  clear renderer
  rendererDrawColor renderer $= V4 255 255 255 255
  drawPoint renderer $ P $ V2 100 100
  present renderer
  appLoop renderer
```
For me, it fails immediately with: `Process exited with ExitFailure (-11)`

The error vanishes if I remove the line `drawPoint renderer $ P $ V2 100 100`, or if I rewrite the whole thing with `getWindowSurface`. Replacing `drawPoint` by e.g. `fillRect ...` or so doesn't help, on the other hand.

Is this a simple mistake on my side?

**Comment by tejon** [comment]
I'm able to run that exact code without issue, using (Haskell) `sdl2-2.4.0.1` and (binary) `SDL2-2.0.4`.

**Comment by turion** [comment]
Ah, then I probably thought right? I guess the problem must be with my system, that is, stack or nixOS. I'll report there, thanks.

**Comment by turion** [comment]
Corresponding nixOS issue: https://github.com/NixOS/nixpkgs/issues/39965
