### ISSUE TITLE
Error running stack with "stack exec"

### ISSUE THREAD

**Issue by jmromeroes** [haskell-game/sdl2#183]
Hi, I'm trying to run this simple project https://github.com/jmromeroes/haskell-chess

But after building it and executing "stack exec haskell-chess-exe" it throws the following error:
_SDLCallFailed {sdlExceptionCaller = "SDL.Image.load", sdlFunction = "IMG_Load", sdlExceptionError = "Couldn't open /home/jose/Documents/emacs-test/haskell-chess/.stack-work/install/x86_64-linux/lts-11.13/8.2.2/share/x86_64-linux-ghc-8.2.2/has"}_
I'm using stack version 1.7.1, libsdl2-dev version 2.0.4 and sdl2 library version 2.4.0.1.

I've tried different versions of everything but it doesn't seem to fix the problem.

**Comment by dpwiz** [comment]
Looks like you need `libsdl2-image-dev` too.

PS: I tried to build your project, but it has too many compile errors ):
