### ISSUE TITLE
Haskell SDL2 bindings not building (Nix)

### ISSUE THREAD

**Issue by bbarker** [haskell-game/sdl2#188]
Hello,

My experience building Haskell packages is extremely limited. I wanted to link to a downstream issue here, in case anyone here has ideas: https://github.com/NixOS/nixpkgs/issues/46130

To be more precise, it builds, but a test fails to run, halting the build chain.

**Comment by typetetris** [comment]
That's just because the test suite `sdl-space` depends on the x server and can't be run in nix build environment and it it could be run, it  fails.

**Comment by ocharles** [comment]
@typetetris is correct. It's probably easiest to just disable tests in `nixpkgs`.
