### ISSUE TITLE
StateVar 1.2

### ISSUE THREAD

**Issue by ekmett** [haskell-game/sdl2#197]
A ([Edit:un-]necessarily) major release of `StateVar` was made to add instances for `ForeignPtr`s. It should break nothing here, so really all that is needed is a version bump on the `StateVar` dependency on hackage to allow `StateVar < 1.3`.

**Comment by ocharles** [comment]
Out of interest, why was that a major release? https://pvp.haskell.org says

> Non-breaking change. Otherwise, if only new bindings, types, classes, **non-orphan instances or modules (but see below) were added to the interface**, then A.B MAY remain the same

(emphasis mine).

StateVar 1.2 just adds an instance, so shouldn't that have permitted a minor bump?

**Comment by ekmett** [comment]
You are correct, sir. I had apparently misremembered this fact.

**Comment by ocharles** [comment]
Cool. No problem, the release is done now so we'll fix up `sdl2` accordingly.

**Comment by ocharles** [comment]
Fixed in https://github.com/haskell-game/sdl2/commit/dba984ae454fe9fc2a104290a30fdfff91ebe676. Preparing a release now
