### ISSUE TITLE
Replace all CInt-s by Int?

### ISSUE THREAD

**Issue by ip** [haskell-game/sdl2#199]
Thank you for this great library. Although, it's called a high-level wrapper around SDL, why do we need to deal with `CInt`, which is from FFI package, in the high-level API? Of course one can convert by `fromIntegral <$> myVec :: V2 Int`, but that's a lot of noise.

**Comment by ocharles** [comment]
We chose to do this because that's what the SDL API is. Int varies in size depending on architecture, which may be wrong

**Comment by ocharles** [comment]
I think I'm going to close this for now, as it would be significantly breaking to change the types now, though if others are OK with that - please chime in. I would encourage a small sdl2 "core" where you do all your marshalling in one place - everything else can stay as `Int`/`Double`/whatever you want to use internally.
