### ISSUE TITLE
Is there any way to access the Raw Event using the high level API?

### ISSUE THREAD

**Issue by dbousamra** [haskell-game/sdl2#203]
I am writing bindings to Imgui. I have a function:

```haskell
ImGui.Internal.Bindings.sdl2ProcessEvent :: GHC.Ptr.Ptr SDL.Event -> IO Bool
```

Is there anyway to access the Ptr value from the high level API, or must I use the raw api?

**Comment by dpwiz** [comment]
No, events get converted quite extensively. One should combine `Raw.peepEvents` + `pollEvent` to get both.
