### ISSUE TITLE
rendererPresentVsync implies rendererAccelerated

### ISSUE THREAD

**Issue by ocharles** [haskell-game/sdl2#21]
> If SDL_RENDERER_PRESENTVSYNC is set without SDL_RENDERER_ACCELERATED, SDL won't find a valid renderer. This is a new problem, possibly related to dropping OpenGL 1.x support. Not sure.
-- https://github.com/openfl/lime/issues/116

However, we allow `presentVsync = True, accelerated = False`, which always throws an exception.

**Comment by tejon** [comment]
Is it necessary to stick with basic types for this, or is it reasonable to have:

    data SDL_Renderer_Accelerated = NotAccelerated | Accelerated | AcceleratedWithPresentVSync

and use that for the `accelerated` value, removing `presentVsync` entirely?

**Comment by polarina** [comment]
That makes sense to me.

**Comment by tejon** [comment]
To document it here -- testing shows a similar issue when SDL_RENDERER_SOFTWARE and SDL_RENDERER_ACCELERATED are both enabled (which makes sense). This is also reflected in my pull request.

**Comment by ocharles** [comment]
Fixed, thanks to @tejon!
