### ISSUE TITLE
Documentation is missing from the latest version on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [haskell-game/sdl2#210]
The documentation for the latest version of this package is missing on Hackage. It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by mherzl** [comment]
I think this might be the same issue:

The 'getting started guide', as linked in the readme
https://hackage.haskell.org/package/sdl2/docs/SDL.html
is not available (returns a 404).

**Comment by dpwiz** [comment]
@ocharles Please upload?

**Comment by ptvirgo** [comment]
I'd also appreciate access to the documentation.

**Comment by wvogel00** [comment]
Now I try access start guide from readme and link, which is written in issue. But I cannot read guide. Where can I read the document?

**Comment by dpwiz** [comment]
> Now I try access start guide from readme and link, which is written in issue. But I cannot read guide. Where can I read the document?

You have to go back a few versions: https://hackage.haskell.org/package/sdl2-2.5.0.0/docs/SDL.html

**Comment by madjestic** [comment]
> > Now I try access start guide from readme and link, which is written in issue. But I cannot read guide. Where can I read the document?
> 
> You have to go back a few versions: https://hackage.haskell.org/package/sdl2-2.5.0.0/docs/SDL.html

That works, but it would be nice to get the documentation of the latest version working too.

**Comment by wvogel00** [comment]
Thank you for your information! I think I can get a general idea of this library for this documentation and the change-log.

**Comment by stridervc** [comment]
I'd also like to be able to view the up to date documentation. The "Getting started guide" linked to from the Readme doesn't even work.

**Comment by ocharles** [comment]
Sorry this took me so long, but it's now updated. Thank you everyone for voicing your feedback - it really helps me prioritize things!
