### ISSUE TITLE
Is `windowSize` not work correctly after window resized?

### ISSUE THREAD

**Issue by ukari** [haskell-game/sdl2#230]
It seems that both `windowSize` and `vkGetDrawableSize` can't get the changed window size. (I am not sure if `glGetDrawableSize` works)

I write an [example](https://github.com/ukari/sdl-resize-example/blob/master/src/Lib.hs) for `windowSize` and test in my computer.

here is the screen record of this test:

https://user-images.githubusercontent.com/10378269/117588600-dd495e00-b113-11eb-83d4-f42c1928d8f0.mp4

**Comment by polarina** [comment]
It is necessary to poll SDL for events in order for the library to recognize that the window has been resized.

**Comment by ukari** [comment]
thanks you!
