### ISSUE TITLE
Compatibility with GHC 9.2 and transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [haskell-game/sdl2#233]
Building with GHC 9.2 and `--allow-newer` already works, so it seems sufficient to bump the  `bytestring` bound. I haven't tried to build with the latest `transformers` yet.

**Comment by Mikolaj** [comment]
Actually I'm not 100% sure if GHC 9.2 and SDL2 work fine together. When I compile 

https://github.com/LambdaHack/LambdaHack

with

    cabal build -w ghc-9.2.1 --allow-newer=witch:base,witch:template-haskell,sdl2:bytestring

I'm getting

    ~/r/LambdaHack$ /home/mikolaj/r/LambdaHack/dist-newstyle/build/x86_64-linux/ghc-9.2.1/LambdaHack-0.11.0.0/x/LambdaHack/noopt/build/LambdaHack/LambdaHack
    LambdaHack: allocaBytesAligned: invalid argument (alignment (=56) must be a power of two!)

after the SDL window opens and closes and the following in gdb (probably something overwrites shared library table):

```
gdb /home/mikolaj/r/LambdaHack/dist-newstyle/build/x86_64-linux/ghc-9.2.1/LambdaHack-0.11.0.0/x/LambdaHack/noopt/build/LambdaHack/LambdaHack
(gdb) run
Starting program: /home/mikolaj/r/LambdaHack/dist-newstyle/build/x86_64-linux/ghc-9.2.1/LambdaHack-0.11.0.0/x/LambdaHack/noopt/build/LambdaHack/LambdaHack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: Corrupted shared library list: 0x485e480 != 0x7ffff7f36078
warning: Corrupted shared library list: 0x485e480 != 0x7ffff7f36078
warning: Corrupted shared library list: 0x485e480 != 0x7ffff7f36078
warning: Corrupted shared library list: 0x4895600 != 0x485e480
warning: Corrupted shared library list: 0x4895600 != 0x485e480
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e8a70 != 0x4895600
warning: Corrupted shared library list: 0x48e93d0 != 0x48e8a70
[New Thread 0x7fffe83b9700 (LWP 22983)]
LambdaHack: allocaBytesAligned: invalid argument (alignment (=56) must be a power of two!)
[Thread 0x7fffe83b9700 (LWP 22983) exited]
[Inferior 1 (process 22978) exited with code 01]
```

At the same time, running with a text frontend is fine

/home/mikolaj/r/LambdaHack/dist-newstyle/build/x86_64-linux/ghc-9.2.1/LambdaHack-0.11.0.0/x/LambdaHack/noopt/build/LambdaHack/LambdaHack --dbgMsgSer --logPriority 4 --boostRandomItem --newGame 9 --maxFps 100000 --benchmark --benchMessages --stopAfterSeconds 1 --dumpInitRngs --automateAll --keepAutomated --frontendTeletype

as well as performing enough SDL2 init phases to load SDL2_ttf fonts:

    /home/mikolaj/r/LambdaHack/dist-newstyle/build/x86_64-linux/ghc-9.2.1/LambdaHack-0.11.0.0/x/LambdaHack/noopt/build/LambdaHack/LambdaHack --dbgMsgSer --logPriority 0 --boostRandomItem --newGame 9 --maxFps 100000 --benchmark --benchMessages --stopAfterSeconds 1 --dumpInitRngs --automateAll --keepAutomated

I can see that both with libsdl2-2.0-0 2.0.4 and with libsdl2-2.0-0 2.0.8, on Ubuntu 16.04, with as new sdl2 Haskell package as possible with these C library version (the latter gives me the newest version from Hackage). With GHC 8.10.7 it all works great.

**Comment by sjakobi** [comment]
Maybe there's a GHC bug involved?! Might be worth reporting…

**Comment by Mikolaj** [comment]
Indeed, I'm waiting for `witch` to update so that the repro is easier. But if any sdl dev has seen such an error message, that may point in another direction, so I'm all ears.

**Comment by Mikolaj** [comment]
OK, so I'm not sure, but probably this is not aligned to a power of two (compare with https://gitlab.haskell.org/ghc/ghc/-/issues/19392#note_331384):

    src/SDL/Raw/Types.hsc-instance Storable Event where
    src/SDL/Raw/Types.hsc:  sizeOf _ = (#size SDL_Event)

**Comment by Mikolaj** [comment]
OK, I updated the repro with everything I got. I think there is a bug in Storable instances in sdl2 (or any of the dependencies), but I don't understand this enough to tell where exactly.

**Comment by dpwiz** [comment]
I suspect `Raw/Types.hsc` doing `alignment = sizeOf` is wrong. I fixed the crash in #236, but more extensive testing is needed.

**Comment by dpwiz** [comment]
Fixed in #236

**Comment by Mikolaj** [comment]
@dpwiz: amazing, thank you. Can we get this ~party started~ version released?

**Comment by dpwiz** [comment]
Waiting on @ocharles to grant hackage rights...

**Comment by ocharles** [comment]
@dpwiz whoops! You have rights now.
