### ISSUE TITLE
Build fails with libsdl2 2.0.20

### ISSUE THREAD

**Issue by Mikolaj** [haskell-game/sdl2#245]
This

```
  pkgconfig-depends:
    sdl2 >= 2.0.6
```

seems inaccurate. It requires sdl2 >= 2.0.10 according to https://github.com/haskell-game/sdl2/issues/240 and it seems to fail with 2.0.20 as seen in https://ci.appveyor.com/project/Mikolaj/allure/builds/42817009

Of course, ideally it'd work with all sdl2 versions, perhaps using cabal flags to juggle compatibility settings.

**Comment by dpwiz** [comment]
Everything is quiet and building for some time.
