### ISSUE TITLE
sdl2 Keyboard events not working

### ISSUE THREAD

**Issue by KadenWolff** [haskell-game/sdl2#254]
I've tried building multiple projects with sdl2 using cabal and stack and I can't seem to get keyboard inputs to work.

I've tried a few of the lazyfoo examples given but keyboard inputs do not work. I can compile and run the equivalent example in C++ without an issue, it handles keyboard events fine.

I also know that it isn't freezing as soon as I run the program. I've tried other examples that have animations and those work fine.

I'm on `Fedora 35`, `cabal-install 3.2.0.0`, `stack 2.7.3`, and `ghc 8.10.5`.

**Comment by nxths** [comment]
Is the SDL2 version on your system 2.0.20, and are you using the latest bindings (https://github.com/haskell-game/sdl2/commit/432f666cf39c6d28037600d465971eb1124f7897)?  This sounds similar to the input issues mentioned in https://github.com/haskell-game/sdl2/issues/245.

**Comment by KadenWolff** [comment]
The SDL2 version on my sytem is 2.0.20 (`sdl2-config --version`) and sdl2 2.5.3.1 (set in cabal).

**Comment by nxths** [comment]
The fixes in current master aren't in the cabal hackage packages yet, you'll need to clone and build from this repo's source for now.  That or downgrade the SDL2 version but that's probably more of a hassle.

**Comment by KadenWolff** [comment]
Gotcha. I'll try this tomorrow and see if it works. Thanks!

**Comment by KadenWolff** [comment]
It works! 

Apologies for the newb question, I'm still somewhat new to Haskell/Cabal. How would I go about using this library now for other projects/what's the simplest way to do that? The lazyfoo examples work in the source library, but I'm unsure how to use this to build my own projects with from here.

If this is too off-topic feel free to close the issue.

**Comment by nxths** [comment]
Hmm yeah getting off topic but for whatever project you can tell cabal to use local packages, e.g. https://stackoverflow.com/questions/63770578/how-do-you-get-cabal-to-install-a-local-package/63776078#63776078

**Comment by KadenWolff** [comment]
Thanks! Closing this then
