### ISSUE TITLE
Support SDL_RenderGeometry

### ISSUE THREAD

**Issue by isovector** [haskell-game/sdl2#261]
I'd like to be able to call these functions https://github.com/libsdl-org/SDL/blob/release-2.0.18/include/SDL_render.h#L1601-L1651

**Comment by dpwiz** [comment]
![Screenshot from 2023-04-19 22-12-55](https://user-images.githubusercontent.com/486682/233177179-65d2c2da-46aa-4692-9e64-b67b65177197.png)
