### ISSUE TITLE
allocaBytesAligned exception when calling `version`

### ISSUE THREAD

**Issue by willmcpherson2** [haskell-game/sdl2#266]
```
$ cabal repl
> import SDL (version)
> version
*** Exception: allocaBytesAligned: invalid argument (alignment (=3) must be a power of two!)
```

sdl2 version 2.5.3.2

GHC version 9.2.2

**Comment by dpwiz** [comment]
Please test the version from `master`. I tried to fix this a few days ago in #264.

**Comment by willmcpherson2** [comment]
@dpwiz Yep, that fixed it. Tested on b4fe21c1025e4be9a1eb03c19f811e1776a2b292. Closing. Thanks!

**Comment by jchia** [comment]
Would you mind making a new release so that stackage nightly can pick it up for the GHC 9.2?

**Comment by dpwiz** [comment]
@jchia Thanks for the reminder. The fix is [live](https://hackage.haskell.org/package/sdl2-2.5.3.3).
