### ISSUE TITLE
The pollEvents function is fixed but pollEvent is still broken

### ISSUE THREAD

**Issue by asvyazin** [haskell-game/sdl2#267]
PR https://github.com/haskell-game/sdl2/pull/242 fixed pollEvents function for SDL 2.0.20 but it didn't fix pollEvent. Is it deprecated?

**Comment by dpwiz** [comment]
This looks as intended.

I imagine you don't want to inject a slow  `pumpEvents` into each and every `pollEvent` call. It looks like you should `pumpEvents` once and then iterate with `pollEvent` until it becomes "empty".

**Comment by asvyazin** [comment]
I did some more research and it looks like `SDL_pollEvent` was indeed broken in SDL 2.0.20 itself (https://github.com/libsdl-org/SDL/issues/5350 and https://github.com/libsdl-org/SDL/issues/5397) and then fixed again by https://github.com/libsdl-org/SDL/commit/6c531c43340af909b95d0814456ef2b828b1ea3c in version 2.0.22

So technically `pumpEvents` is not necessary but it can be... depending on SDL version. Anyway good to know it's not an issue here

**Comment by dpwiz** [comment]
Good lord... And now we're stuck with broken 2.0.20 in Ubuntu LTS for quite a few years unless Canonical does a backport :woman_facepalming:
