### ISSUE TITLE
No Wayland support

### ISSUE THREAD

**Issue by MonAaraj** [haskell-game/sdl2#270]
Hello! I have been trying to get a program I've written to work in Wayland by setting the environment variable
 `export SDL_VIDEODRIVER=wayland`
but I get this error:
` SDLCallFailed {sdlExceptionCaller = "SDL.Init.init", sdlFunction = "SDL_Init", sdlExceptionError = "wayland not available"}`

From what I know, SDL2 already supports Wayland at this point; so I am rather confused how it doesn't work with `sdl2`.

**Comment by ocharles** [comment]
I think it would help to see a C sample that works for you on Wayland. Next, we can see if we can get it working in Haskell.

**Comment by MonAaraj** [comment]
https://bpa.st/USTA
This is a very {bad,small} example. It creates a white window. If I run it with `SDL_VIDEODRIVER=wayland`, then it uses Wayland instead of XWayland. But if I try any Haskell sdl2 project with that environment variable, I get the aforementioned error.

**Comment by MonAaraj** [comment]
Oh, sorry. Misclicked!

**Comment by MonAaraj** [comment]
I'm having a problem that is blocked by this issue, as it looks like no form of mouse position reporting works at all if it's not running on Wayland. What's the progress on this?

**Comment by ocharles** [comment]
I'm afraid I don't think anyone is actively looking at this at the moment.

**Comment by MonAaraj** [comment]
This doesn't *quite* mimic the C, but it does most of it: https://bpa.st/ZCXQ
So, here's the conclusion I've arrived at: In haskell sdl2, surfaces are *not* Wayland compatible. But textures are.

**Comment by dpwiz** [comment]
The bpa.st links are all 404d out )=

**Comment by coder3112** [comment]
@MonAaraj can you please either 
 1. Revive the links you gave
 2. Post the minimal, reproducible example in the comments themselves so that they are (more) permanent.
Thanks!

**Comment by MonAaraj** [comment]
I can't exactly revive them, but I can give you a """minimal""" reproducible example.
<details><summary>Main.hs</summary>

```hs
#!/usr/bin/env cabal
{-# LANGUAGE OverloadedStrings #-}

{- cabal:
build-depends: base, sdl2, text, linear
-}

import SDL
import Linear (V4(..))
import Control.Monad (unless)

main :: IO ()
main = do
  initializeAll
  window <- createWindow "My SDL Application" defaultWindow
  renderer <- createRenderer window (-1) defaultRenderer
  screen <- getWindowSurface window
  appLoop renderer
  destroyWindow window

appLoop :: Renderer -> IO ()
appLoop renderer = do
  events <- pollEvents
  let eventIsQPress event =
        case eventPayload event of
          KeyboardEvent keyboardEvent ->
            keyboardEventKeyMotion keyboardEvent == Pressed &&
            keysymKeycode (keyboardEventKeysym keyboardEvent) == KeycodeQ
          _ -> False
      qPressed = any eventIsQPress events
  rendererDrawColor renderer $= V4 0 0 255 255
  clear renderer
  present renderer
  unless qPressed (appLoop renderer)
```
</details>

As mentioned earlier, if you run this with `SDL_VIDEODRIVER=wayland`, then it says:
`script: SDLCallFailed {sdlExceptionCaller = "SDL.Video.getWindowSurface", sdlFunction = "SDL_GetWindowSurface", sdlExceptionError = "No hardware accelerated renderers available"}`

But, if I don't use surfaces at all, instead only textures, then it works fine for Wayland.

**Comment by hanst99** [comment]
@MonAaraj Using a screen surface together with the `SDL_Renderer` API like you're doing here is not supported by SDL itself: [see documention](https://wiki.libsdl.org/SDL_GetWindowSurface). This API is mostly outmoded anyway, it's more useful as a temporary utility for porting SDL1.x code. Using a screen surface by their nature keeps you from using hardware accelerated rendering, which is not what you want because software rendering is somewhere on the order to thousands to millions of times slower than accelerated, depending on what exactly you're doing.

**Comment by MonAaraj** [comment]
Alright, thank you very much. I will be closing this issue.

**Comment by dpwiz** [comment]
I wonder what would be a correct place to put the wayland/texture notice. Should the entire `Surface` block get a heads-up /  deprecation notice? :thinking:
