### ISSUE TITLE
Possibly unreproducible bug uncontrollably redirecting input. (win10)

### ISSUE THREAD

**Issue by liamzee** [haskell-game/sdl2#284]
I was playing around with the streamly examples for circling rectangles, and one interesting thing I found is that at present, using ghc to directly compile a small package, well, here's the funny thing.

If you compile with GHC, and have a main that only IMPORTS the module SDL, and then putStrLn s "hello world", the hello world is eaten up by SDL and never printed to the console. Take out the import, and the "hello world" is printed again to the console.

I get the feeling that this might not be reproducible, however.

===

Some further testing seems to indicate that this bug is triggered by passing the -package sdl2 flag to ghc directly. I'm going to trial again with cabal.

**Comment by dpwiz** [comment]
I vaguely remember the symptoms... Perhaps something like this would help?

```
  if os(windows)
    ghc-options: -optl-mconsole
```

**Comment by Poselsky** [comment]
Yep. Everytime I'm building on windows platform I also have to add this flag. Can we put this into readme to make it more obvious?

**Comment by liamzee** [comment]
Set via pkgconfig, problem fixed.
