### ISSUE TITLE
Make `sdl2` compatible with `base` < 4.11

### ISSUE THREAD

**Issue by ivanperez-keera** [haskell-game/sdl2#310]
The module `SDL.Input.Mouse` assumes that `(<>)` is defined in `Prelude`, but that only happened in `base` 4.11. Until then, the symbol was defined in `Data.Semigroup`, and another is defined in `Data.Monoid` (for some types, the two are equivalent).

It's being used here: https://github.com/haskell-game/sdl2/blob/master/src/SDL/Input/Mouse.hs#L307

We are trying to move `dunai` to use `sdl2`, and we are hitting a problem with supporting older versions of GHC.

Would it be possible to add a conditional import so that `sdl2` compiles with older versions of GHC as well?

Since `<>` is used on `String`s, which are lists of characters, and lists are monoids, then it's safe to pick the version from `Data.Monoid` because they are equivalent per the definition of [Semigroup](https://hackage.haskell.org/package/base-4.10.1.0/docs/src/Data.Semigroup.html#local-6989586621679384451):

```haskell
class Semigroup a where
  (<>) :: a -> a -> a

  default (<>) :: Monoid a => a -> a -> a
  (<>) = mappend
```

Therefore, something along the following lines would do:

```haskell
#if !MIN_VERSION_base(4,11,0)
import Data.Monoid ((<>))
#endif
```

**Comment by ocharles** [comment]
base-4.11 is over 4 years old. Pre 4.11 puts you all the way back to GHC 8.2. I'm not sure we've ever decided what our support policy is, but that is a whopping huge window and not sure we have the resources to actually commit to that

**Comment by ivanperez-keera** [comment]
From the current version of the same file:

https://github.com/haskell-game/sdl2/blob/5c92d46bebf188911d6472ace159995e47580290/src/SDL/Input/Mouse.hs#L67-L69

Those three lines help support the GHC 7 series.

All I'm asking is if you'd accept a 3 line patch in the same file.

**Comment by ocharles** [comment]
Of course we could accept such a patch, I'm just saying don't expect it to not just break again :)

**Comment by ivanperez-keera** [comment]
Thanks!

I've sent a PR. I tried it with GHC 7.10 (which [this current import](https://github.com/haskell-game/sdl2/blob/5c92d46bebf188911d6472ace159995e47580290/src/SDL/Input/Mouse.hs#L67-L69) refers to) and it compiles.

**Comment by ivanperez-keera** [comment]
This has now been merged into the main branch.
