### ISSUE TITLE
Support for extension libraries

### ISSUE THREAD

**Issue by marchelzo** [haskell-game/sdl2#38]
Are there plans to support sdl2_ttf et al.? In particular I would like to load fonts and render text, but I don't believe it has been implemented yet.

**Comment by Mokosha** [comment]
This is a tricky subject -- sdl2_ttf et al. are separate libraries from sdl2. In my opinion it's probably better to have separate repositories for their haskell bindings that interop with this library rather than including them here.

**Comment by mankyKitty** [comment]
@marchelzo I have an implementation of the sdl2_ttf bindings up on Hackage at the moment. The github repo is here https://github.com/mankyKitty/sdl2-ttf 

They are designed to use the haskell-game/sdl2 repo and I'm trying to keep them up to date with this library. :)

**Comment by marchelzo** [comment]
@mankyKitty Awesome. Thank you for letting me know about it.
