### ISSUE TITLE
How about pushing this new version to hackage and stackage ?

### ISSUE THREAD

**Issue by rvion** [haskell-game/sdl2#42]

**Comment by polarina** [comment]
I do not believe the library is currently in an acceptable state to be released.

Documentation is missing, and we do not yet expose internals to allow for interopability between the high- and low-level interfaces.

At the very least, I'd like those to be resolved first before issuing a release.

**Comment by rvion** [comment]
Thanks for the heads up, that is exactly what I wanted to know
