### ISSUE TITLE
Can’t install on Windows

### ISSUE THREAD

**Issue by phaazon** [haskell-game/sdl2#43]
```
$ cabal install --only-dependencies
Resolving dependencies...
Notice: installing into a sandbox located at
C:\Users\phaazon\dev\quine\.cabal-sandbox
Configuring sdl2-1.3.0...
Failed to install sdl2-1.3.0
Build log ( C:\Users\phaazon\dev\quine\.cabal-sandbox\logs\sdl2-1.3.0.log ):
Configuring sdl2-1.3.0...
setup-Simple-Cabal-1.22.1.1-i386-windows-ghc-7.8.3.exe: The program
'pkg-config' version >=0.9.0 is required but it could not be found.
cabal.exe: Error: some packages failed to install:
sdl2-1.3.0 failed during the configure step. The exception was:
ExitFailure 1
```

I tried to install `pkg-config`, guess what, it doesn’t exist. :(

**Comment by Kludgy** [comment]
`pkg-config` is not a Haskell package. It is a common tool on Linux distros, but is also available for Windows. More info at [1].

You have a few options here:
1. Probably the most popular way to get pkg-config installed in WIndows is to install GTK+. [2]
2. Another approach is to use a package manager like Chocolatey [3], which provides a solution analogous to command line package managers on other OS distros.
3. Yet another option (the one I use) is to install MSYS2 [4] and issue `pacman -S pkg-config`.

Hope this helps. It is a common stumbling block for Windows devs.

----
[1] http://en.wikipedia.org/wiki/Pkg-config
[2] http://www.gtk.org/download/win32.php (or corresponding win64 link)
[3] https://chocolatey.org/packages/pkgconfiglite
[4] http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

**Comment by phaazon** [comment]
`pacman` on Windows? SERIOUSLY?! NEED.

**Comment by Kludgy** [comment]
It really depends on what your tool chain needs are. MSYS2 is probably the most aligned with most development via GHC at this point in time since this is used to build GHC itself.

**Comment by expipiplus1** [comment]
For a quick fix you could apply this patch: https://gist.github.com/anonymous/9d1060281ed7127a54d2 It removes the need for any package manager, and manually puts int the dependency on mingw32 and sdl2main

**Comment by nxths** [comment]
Placing the pkg-config.exe from pkg-config-dev_0.26-1_win32.zip http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/ in the Windows PATH works for me

**Comment by tejon** [comment]
Windows story is in pretty good shape now.
