### ISSUE TITLE
"import SDL" fails on fresh install.

### ISSUE THREAD

**Issue by JavierJF** [haskell-game/sdl2#51]
The system details are:
ArchLinux x64,  GHC Version 7.10.1, stage 2 booted by GHC version 7.8.4, cabal-install version 1.22.2.0.

I have removed all previous libraries to avoid possible package corruption. All libraries were installed in a fresh install of GHC and Cabal. And compiling "sdl2/examples/lazyfoo/Lesson01.hs" gives the error: 

src/App/Main.hs:7:18:
    Could not find module ‘SDL’
    Use -v to see a list of the files searched for.

**Comment by polarina** [comment]
Are you installing `sdl2` from Hackage, or compiling from the `new-api` branch here on Github?

**Comment by JavierJF** [comment]
From Hackage, i didn't saw instructions about compiling it from here. Should I?

**Comment by polarina** [comment]
Yes. The examples are only applicable to the `new-api` version.

**Comment by JavierJF** [comment]
Thanks you. Would you like if I make a patch for the readme?

**Comment by polarina** [comment]
I wouldn't mind. Keep in mind though that this is a development version we eventually would like to release on Hackage.
