### ISSUE TITLE
sdl-mixer?

### ISSUE THREAD

**Issue by nomeata** [haskell-game/sdl2#52]
In order to migrate away from the `SDL` haskell package to SDL2 and your bindings, I would need `SDL_mixer` bindings. Do you have any plans to support that?

Thanks,
Joachim

**Comment by sbidin** [comment]
Not sure about haskell-game, but @tempname11 and me have done some work on bindings to `SDL2_mixer`. They are currently still in an early state and welcoming patches, but should be usable. You can find the latest version [here](https://github.com/sbidin/sdl2-mixer).

**Comment by nomeata** [comment]
Thanks for the pointer! I want to use SDL-mixer for its convenience (and that of my users),so I’ll wait until it is on hackage.
