### ISSUE TITLE
createRGBSurfaceFrom is dangerous

### ISSUE THREAD

**Issue by tempname11** [haskell-game/sdl2#56]
As it is, it accepts a (Data.Vector.Storable.Vector Word8) as it's "pixel data" argument, and the implementation uses 'unsafeWith' to get the underlying memory pointer, in order to pass it to SDL_CreateRGBSurfaceFrom. However, https://wiki.libsdl.org/SDL_CreateRGBSurfaceFrom says:

"No copy is made of the pixel data. Pixel data is not managed automatically; you must free the surface before you free the pixel data."

Moreover, the SDL Surface API assumes that this surface memory may be mutated (see https://wiki.libsdl.org/SDL_LockSurface).

So, obviously this is wrong. There are several paths we could go here, and I'm not sure which is best:

1) The interface remains as is, and a copy of the memory is made internally. The high-level Surface object keeps a reference to this memory and it is be freed appropriately from "destructors".

2) The interface is changed to a MVector (mutable vector). The Surface object keeps a reference to the mutable vector to avoid it's garbage collection. The documentation should mention something about locking the surface for mutation.

3) The interface is changed to a Ptr, no references are kept, the documentation should state clearly that the user must manage memory manually.

So far, (2) looks best to me, however, I'm not at all familiar with MVector and so may miss an obvious issue with this approach. (1) seems wasteful, and (3) too low-level. And of course, there probably is some better way. Opinions?

**Comment by polarina** [comment]
I personally like option (2), it looks like to be the most convenient option for the user without any obvious drawbacks.

**Comment by tempname11** [comment]
I created a potential pull-request, but there are subtle details that might necessitate its rejection. See more in the pull-request message.
