### ISSUE TITLE
sdl2 falling behind ?

### ISSUE THREAD

**Issue by PinkMushroom** [haskell-game/sdl2#71]
I just installed ghc 7.10.2 and that required me to update some packages.

sdl2 then failed to build because:

linear is now 1.19.1.3
vector is now 0.11.0.0

Both seem like very minor version upgrades.
i've rebuilt, making the appropriate changes to the .cabal file and ran a very (very) basic test using
haskell-sdl2gl and things seem to work fine.

**Comment by deepfire** [comment]
The `newapi` branch also fails against current linear in NixOS:
```
Configuring sdl2-2.0.0...
Setup: At least the following dependencies are missing:
linear >=1.10.1.2 && <1.19
builder for ‘/nix/store/vlwxgpnyzqzqmaq2rpq81j4ylyqhvdzi-haskell-sdl2-1.3.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/6pccy4gj56nxlcknjc25nkjfr941kdgi-ghc-7.10.2.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/6pccy4gj56nxlcknjc25nkjfr941kdgi-ghc-7.10.2.drv’ failed
```

**Comment by ocharles** [comment]
Now fixed
