### ISSUE TITLE
RenderM monad?

### ISSUE THREAD

**Issue by ocharles** [haskell-game/sdl2#8]
What do people think about this:

```haskell
newtype RenderM a = RenderM { runRenderM :: Renderer -> IO a }
  deriving (Monad, Functor, Applicative, MonadReader Renderer, MonadIO, etc)
```

The idea being that when you're working with a renderer almost everything needs a pointer to the renderer, which is a lot of annoying plumbing. Maybe it's nicer to abstract this out with a reader monad?

**Comment by ocharles** [comment]
I'm not sure this really makes sense now that we have moved to `StateVar`. The problem being that the `StateVar` can only work in `IO`, but in order to access the `Renderer` you need to be in a different monad (presumably some `MonadReader Renderer m`). 

We could have things like

```haskell
renderDrawColor :: MonadReader Renderer m => m (StateVar (V4 Word8))
```

which then works as

```haskell
renderDrawColor renderer $= V4 255 128 0 255
```

but also

```haskell
renderDrawColor >>= ($= V4 255 128 0 255)
```

but that's pretty weird :/

If `StateVar` gave us non-infix names it gets a bit better:

```haskell
renderDrawColor >>= set (V4 255 128 0 255)
```

but that is still not a very appealing API.

Pinging @polarina before I close this, but I'm not sure this is a workable API

**Comment by ocharles** [comment]
It's worth noting that if we *only* want people to use the monadic interface, then we could use `reflection` or other tricks to pass the implicit parameter around:

```haskell
renderDrawColor :: Reify s Renderer => StateVar (V4 Word8)
```

Interaction is then just

```haskell
renderDrawColor $= V4 255 128 0 255
```

However, I don't think you can do that either, because `s` is ambiguous - it probably needs a `proxy s` to be passed around too, so we're stuck again!

**Comment by tejon** [comment]
I don't think this is an idea that should be given up on, but at the same time, it seems like a higher-level concern to me. Hard line to draw, since the big goal of this revision is to make the API more idiomatic, but I think this crosses it. Total functions and excluding illegal configurations via types are universally Good Haskell; monads are popular, but I don't think anyone would claim that they're the Only Right Way, and I've seen a few rants *against* `do` notation.

So yeah, save it for another package IMO.

**Comment by ekmett** [comment]
`renderDrawColor :: Reify s Renderer => StateVar (V4 Word8)` doesn't work. You need the 's' _somewhere_ on the right hand side of the =>`.

**Comment by ocharles** [comment]
I know, I said exactly that :)
