### ISSUE TITLE
Any plan to support sdl2-image etc?

### ISSUE THREAD

**Issue by carldong** [haskell-game/sdl2#93]
I am writing a game library using sdl2 ([timeless-RPG](https://github.com/carldong/timeless-RPG)). This is a really nice library wrapped around SDL2! Are there any plans to support other modules? 

Thanks

**Comment by ocharles** [comment]
I think this is a duplicate of issue https://github.com/haskell-game/sdl2/issues/79 - would you agree? tl;dr - yes there is interest! :smile:

**Comment by afwlehmann** [comment]
Any plans to close this issue? I also tend to think it's a duplicate of #79.
