### ISSUE TITLE
Release version compatible with lens-4.13 and linear-1.20

### ISSUE THREAD

**Issue by DanBurton** [haskell-game/sdl2#96]
It seems the github repo is already at this point. This issue is just a reminder to cut a release to hackage. sdl2 is one of the final puzzle pieces to upgrading lens and linear on stackage nightly. See https://github.com/fpco/stackage/issues/832

**Comment by ocharles** [comment]
Thanks for the notification Dan! I'll try and get a new version pushed out
ASAP.

**Comment by ocharles** [comment]
`sdl2-2.1.0` released.

**Comment by DanBurton** [comment]
Nice!
