### ISSUE TITLE
sdl2-2.1.0 Hackage documentation is broken

### ISSUE THREAD

**Issue by TerrorJack** [haskell-game/sdl2#97]

**Comment by cocreature** [comment]
They're not broken, Hackage just hasn't gotten around to building them. The status says “Docs pending”.

**Comment by TerrorJack** [comment]
@cocreature Thanks for clarifying.

**Comment by ocharles** [comment]
I doubt Hackage will be able to build documentation due to the C library
dependency. I'll be home tomorrow to have a look if it hasn't built by then.

**Comment by TerrorJack** [comment]
@ocharles On Hackage, the status now says "Docs not available", so it is indeed broken.

**Comment by TerrorJack** [comment]
Seems that the Hackage docs are already uploaded.

**Comment by ocharles** [comment]
Yep, I uploaded them yesterday but forgot to close this - thanks!

**Comment by ivanperez-keera** [comment]
Sorry for commenting on a closed issue.

Both the docs and the build fails, giving sdl2 a bad image (for those who want to start doing game programming and need to be sure their efforts won't be wasted). This also happens to qt, but not Gtk. 

What would be the best way to approach this? Contact the hackage maintainers and tell them to have libsdl2-dev (& friends) and libqt4-dev installed in their machines?

**Comment by ocharles** [comment]
Yes, I believe that's the only option - other than manually uploading documentation.
